version: '3.8'
services:
  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filemanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  angular-app:
    build:
      context: ./front/file-manager
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: filemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge